### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes' 

### ISSUE THREAD

**Issue by alandtse** [Klikini/doorbirdpy#1]
In my homeassistant environment running python 3.4, doorbirdpy returns a TypeError when json.loads:

```
Traceback (most recent call last):
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/doorbirdpy/__init__.py", line 35, in ready
    code = json.loads(content)["BHA"]["RETURNCODE"]
  File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```
This appears to be related to content requiring decoding of UTF-8.

The solution appears to be to replace every instance of:
`json.loads(content)
`with 
`json.loads(content.decode('utf-8'))
`

**Comment by Klikini** [comment]
https://pypi.python.org/pypi/DoorBirdPy/0.1.0

**Comment by Klikini** [comment]
It's on PyPi now, so the version just needs to be updated to 0.1.0 in HA. Thank you!
